// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import fasthttp "github.com/valyala/fasthttp"
import mock "github.com/stretchr/testify/mock"
import time "time"

// FastHttpClient is an autogenerated mock type for the FastHttpClient type
type FastHttpClient struct {
	mock.Mock
}

// DoTimeout provides a mock function with given fields: req, resp, timeout
func (_m *FastHttpClient) DoTimeout(req *fasthttp.Request, resp *fasthttp.Response, timeout time.Duration) error {
	ret := _m.Called(req, resp, timeout)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fasthttp.Request, *fasthttp.Response, time.Duration) error); ok {
		r0 = rf(req, resp, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
